appdynamics-cloud-k8s-monitoring:
  clustermonConfig:
    clusterName: terraform-aks-charleslin-cluster
    events:
      enabled: true
      severityToExclude: []
      reasonToExclude: []
      severeGroupByReason: []
  install:
    logCollector: true
 
  logCollectorConfig:
    container:
      conditions:
        - condition:
            operator: contains
            key: kubernetes.pod.name
            value: ad-service
          messageParser:
            log4J:
              enabled: true
              pattern: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} %n"
          multiLinePattern: '^2022' # default is after
          multiLineNegate: true # default is false
      clusterName: terraform-aks-charleslin-cluster
      dropFields: ["agent", "stream", "ecs", "input", "orchestrator", "k8s.annotations.appdynamics", "k8s.labels", "k8s.node.labels", "cloud"]
      batchSize: 1000
      loggingLevel: info
      loggingSelectors: [ "otlp" ]
    
appdynamics-otel-collector:
  # see collectors-values-sensitive.yaml for the following setting
  # clientId: <clientId>
  # clientSecret: <clientSecret>
  # tenantId: <tenantId>
  # endpoint: https://lab1.observe.appdynamics.com

